
node('linux') {


     stage('Setup'){
            git credentialsId: 'access-jenkins', url: 'https://github.com/UST-SEIS665/hw11-seis665-02-spring2019-nyaundid.git'
            

     
            sh 'aws s3 cp s3://jenkinsw12/classweb.html /workspace/docker-pipeline/index.html'
                
        
    }
    
      stage('Build'){
       
       sh 'docker build -t classweb:1.0 .'
   
 

          
    }

    
    stage('Test'){
       sh 'docker stop classweb1'  
       sh 'docker rm classweb1'  
         
       sh 'docker run -d --name classweb1 -p 80:80 --env NGINX_PORT=80 classweb:1.0'
         
         
       sh 'curl -s 172.17.0.3'  

      sh 'docker inspect --format {{.NetworkSettings.IPAddress}} classweb1' 
   }
}
